/* Shared article content for the Whiskers Journal */
const ARTICLES = {
  litterbox: {
    tag: "Litter & Hygiene",
    title: "Why some cat owners are quietly breaking up with their litter robot",
    excerpt: "Self-cleaning litter boxes promise to end scooping forever. Six months in, a lot of owners discover the catch — here's what to weigh before you buy.",
    meta: "7 min read · Litter & Hygiene",
    img: "images/litter-robot.svg",
    related: ["c14", "c13", "c15"],
    body: [
      { lead: "For a few glorious years, the self-cleaning litter box looked like the gadget that would finally end scooping forever. Lately a quieter story has been spreading through cat-owner forums — and it's worth hearing before you spend a few hundred dollars." },
      { h2: "The first month really is that good" },
      { p: "Nobody's lying about the honeymoon. The machine hums through its cycle, the litter bed looks immaculate, and the daily ritual of scoop-and-sigh just… stops. In a small apartment, or a house with three cats and a full-time job, that first month can feel genuinely life-changing." },
      { p: "The trouble is that the early magic hides a slower story. Most owners don't notice the real upkeep until a few months in, when dust, moisture and residue have quietly been collecting in places the cleaning cycle never touches." },
      { h2: "‘Self-cleaning’ and ‘clean’ are not the same thing" },
      { p: "This is the gap between the ad and the reality. A self-cleaning box separates waste out of the litter bed — it doesn't actually clean the machine. The visible tray stays pristine while gunk builds up in all the spots you can't see." },
      { ul: ["Under the rotating drum", "Around the rubber seals", "Near the waste port", "Along the sensor edges", "Inside the internal plastic joints"] },
      { p: "For a while it's easy to ignore, because the part you look at still sparkles. Then comes the sour smell that survives emptying the drawer — and the realisation that properly deep-cleaning a bulky, motorised unit means lugging it to the shower. A plain tray is ugly, but it's a thirty-second rinse." },
      { pull: "A spotless-looking litter bed can sit on top of a machine nobody has properly cleaned in weeks." },
      { h2: "Odour control is better than it used to be — but not solved" },
      { p: "Sealed drawers, carbon filters and deodorising tricks genuinely help at the start. Long term, the weak point is the residue that creeps onto internal surfaces, where bacteria settles in somewhere you can't easily wipe. Cheaper plastics drink up odour, and fully enclosed designs can trap moisture and make things worse. Tellingly, the question shoppers now ask has shifted from ‘does it kill the smell?' to ‘how hard is this to clean after six months?'" },
      { h2: "More technology, more things to troubleshoot" },
      { p: "App-connected everything felt futuristic a few years ago. Now there's a quiet fatigue: flaky Wi-Fi pairing, firmware updates that fail, late notifications, sensors that misread. The honest bit is that most of those features aren't why anyone bought a litter box. You wanted less daily work, not another device to manage — which is why plain reliability is becoming the real premium." },
      { h2: "The safety question changed how people shop" },
      { p: "Modern boxes use weight or infrared sensors to stop moving the moment a cat steps in, and the vast majority work exactly as intended. But owners have close to zero tolerance for mechanical risk around their animals, so a single alarming clip online travels fast. Shoppers now actively look for anti-pinch design, an emergency stop and detection that's clearly been tested — and that scepticism is completely fair." },
      { h2: "Plenty of people happily keep theirs" },
      { p: "None of this means the category is a mistake. For the right household the trade is clearly worth it — the box earns its keep every single day." },
      { ul: ["Multi-cat homes drowning in scooping", "Frequent travellers who need a few days' buffer", "Anyone with mobility limitations", "People with punishing work schedules"] },
      { p: "For a single cat in a small flat, though, a well-designed covered tray and a good low-dust, odour-control litter often wins on every measure that matters: cheaper to run, nothing to update, fewer parts to fail, and quick to sanitise properly." },
      { h2: "What we'd actually tell a friend" },
      { p: "If you buy a self-cleaning box, buy for maintenance, not marketing: removable internal parts, smooth washable surfaces, and a structure you can take apart without a manual. Pair it with a low-dust, odour-control litter, and commit to a real deep clean every couple of weeks. If that sounds like a chore you won't keep up, there is genuinely no shame in a beautifully simple covered tray — your cat, frankly, could not care less which one looks cleverer." },
      { p: "Whichever way you lean, the litter aisle is one place we'd rather sell you the thing that quietly works than the thing with the most blinking lights. Browse our litter & hygiene range and pick the one that fits your home — not your group chat." },
    ],
  },
  sleep: {
    tag: "Feline Wellness",
    title: "Is your cat sleeping too much — or exactly the right amount?",
    excerpt: "They sleep 16 hours a day and still look exhausted. How much is normal — and the comfiest beds for serious nappers.",
    meta: "4 min read · Wellness",
    img: "images/splayed.jpg",
    related: ["c7", "c8", "c9"],
    body: [
      { lead: "If your cat appears to be unconscious for most of the daylight hours, congratulations: you have a normal cat." },
      { h2: "How much is normal?" },
      { p: "Adult cats sleep between 12 and 16 hours a day, and kittens and seniors often clock even more. It's a hard-wired hunter's rhythm — short bursts of intense activity followed by long, luxurious recovery. The dramatic 3am sprint down the hallway is part of the same system." },
      { p: "What matters isn't the total hours so much as the pattern. A cat that's still playful, eating well and grooming normally is simply doing cat things. A sudden change — much more sleep, much less, or a cat that seems flat and withdrawn — is worth keeping an eye on." },
      { pull: "A cat doesn't sleep because it's bored. It sleeps because it has decided the day is beneath it." },
      { h2: "Give them a bed worth the commitment" },
      { p: "Cats are connoisseurs of comfort and microclimate. A supportive, draught-free bed in a warm, slightly elevated spot will almost always win out over the laundry pile — eventually. Orthopaedic bases help older cats, raised rims satisfy the instinct to feel enclosed, and a sunny window perch is, frankly, unbeatable." },
      { p: "If your cat is ignoring a perfectly good bed, try moving it somewhere with a view and a sunbeam. Location beats luxury nearly every time." },
    ],
  },
  cattree: {
    tag: "Enrichment",
    title: "The complete guide to choosing a cat tree they won't ignore",
    excerpt: "Height, material, sisal vs carpet, pod vs platform. A practical breakdown of what actually gets used.",
    meta: "6 min read · Lifestyle",
    img: "images/bubble-tree.jpg",
    related: ["c8", "c11", "c10"],
    body: [
      { lead: "The internet is full of magnificent cat trees gathering dust in living rooms. Here's how to buy one that earns its floor space." },
      { h2: "Height is the whole point" },
      { p: "Cats feel safest when they can survey their domain from above. A tree that lets them perch higher than the surrounding furniture will almost always beat a shorter, fancier one. If you only optimise for one thing, optimise for height." },
      { h2: "Sisal beats carpet" },
      { p: "For scratch surfaces, sisal rope is the gold standard: it's coarse enough to satisfy the urge and durable enough to survive it. Carpet-wrapped posts tend to shred and, worse, can teach a cat that carpet is fair game — including the carpet you'd rather keep." },
      { pull: "Buy the tree your cat would buy, not the one that matches your couch." },
      { h2: "Pods, platforms and placement" },
      { p: "Enclosed pods suit nervous or cuddly cats; open platforms suit the watchful, social type. Most cats want a mix. Wherever it goes, place it near a window or a busy room — a cat tree in a quiet corner is a cat tree in exile." },
      { h2: "Stability matters more than looks" },
      { p: "A wobbly tree is a rejected tree. Look for a wide, weighted base and solid joinery. If it shifts when they leap, they'll learn not to leap — and then it's just expensive furniture." },
    ],
  },
  kitten: {
    tag: "Kitten Care",
    title: "Everything you need in the first 8 weeks with a new kitten",
    excerpt: "Food, beds, litter, toys and carriers — the complete shopping checklist for the chaos ahead.",
    meta: "8 min read · Kitten",
    img: "images/kittens-sleeping.jpg",
    related: ["c1", "c13", "c6"],
    body: [
      { lead: "A new kitten is roughly nine percent animal and ninety-one percent enthusiasm. Here's the shopping list that makes the first two months smoother." },
      { h2: "Food first" },
      { p: "Kittens grow fast and need a complete kitten-specific formula to match. Pick one high-quality food and transition gradually if you're switching from what the breeder or shelter used — sudden changes upset small stomachs." },
      { h2: "Litter and logistics" },
      { p: "Start with a low-sided tray and an unscented, low-dust litter so tiny paws can get in and out easily. Put it somewhere quiet and consistent; kittens are creatures of habit almost immediately." },
      { h2: "Sleep and safety" },
      { p: "A soft, enclosed bed in a calm corner gives a new kitten somewhere to retreat. Expect them to ignore it for the sock drawer at least once. A sturdy carrier is non-negotiable for the trip home and the trips that follow." },
      { pull: "Buy the carrier before you need it. You will always need it sooner than you think." },
      { h2: "Play is not optional" },
      { p: "Wand toys, soft balls and a treat-dispensing puzzle channel all that energy into something other than your ankles. Ten minutes of structured play, twice a day, works wonders — for both of you." },
      { h2: "The short checklist" },
      { ul: ["Complete kitten food", "Low-dust litter and a low tray", "A soft, enclosed bed", "A sturdy carrier", "Wand toy + a couple of soft toys", "Scratching post (start the habit early)", "Food and water bowls"] },
    ],
  },
};
if (typeof module !== "undefined") module.exports = { ARTICLES };
